version: "2"
services:
    www:
        build: .
        ports: 
            - "8002:80"
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.6.37
        ports: 
            - "3309:3306"
        environment:
            MYSQL_DATABASE: seedms_db
            MYSQL_USER: user
            MYSQL_PASSWORD: testIIEG2022
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: testIIEG2022
            TZ: America/Mexico_City
        volumes:
            - ./seeddms/dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8004:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: testIIEG2022
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: testIIEG2022
volumes:
    persistent: